### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jamie-arcc** [JuliaComputing/Swagger.jl#10]
It seems that documentation, especially about how to actually use this package, is somewhat inadequate and missing things.  I am currently trying to use this to generate an API wrapper based on a Swagger file and so far am having no luck.  I was able to successfully run the petshop test by hand, however, by following the generate.sh script in there.  It seems that there are undocumented options in the config.json file, and those may be what I am missing in mine.  This package is potentially very useful, but it also needs to be usable.  Thanks!

**Comment by pbarker** [comment]
second this, I spent the morning trying to build this in a docker container and was unsuccessful. It seems that after building the jar and running the generate script java can't find it `Error: Could not find or load main class io.swagger.codegen.SwaggerCodegen`. The main issue here is that most Julia folks aren't good at Java, would be better if we could make this turn key.
