### ISSUE TITLE
Merge with Swagger.io

### ISSUE THREAD

**Issue by aviks** [JuliaComputing/Swagger.jl#3]
Can we contribute this to upstream? 

https://github.com/swagger-api/swagger-codegen/issues/4815

Or open this repository up?

**Comment by tanmaykm** [comment]
A README is not there yet, but the repo is now open.

**Comment by ViralBShah** [comment]
@aviks - can you announce it on discourse?

**Comment by ViralBShah** [comment]
And also our blog?
