### ISSUE TITLE
missing swagger input or config!

### ISSUE THREAD

**Issue by ebigram** [JuliaComputing/Swagger.jl#50]
Really wish I could use this library but running out of ideas after trying under three different operating systems (Linux, Win11, OSX), with all the combinatorics of Maven/Java versioning. It builds fine, and there are no errors besides the one in the title; I copy-pasted the instructions from the readme substituting my the vars with my own files and setting packageName in the JSON file. I have experience with Swagger for other projects so confirmed I am able to use codegen to target other language clients.

Do you mind sharing precisely which Java/MVN versions you've known to be compatible with it? Thanks, this looks very promising!

**Comment by tanmaykm** [comment]
That's strange. From what I see, `missing swagger input or config!` is thrown when the code generator is not able to read the specifications file.

And though I think it should work with different Java versions, what is used in CI for example is https://github.com/JuliaComputing/Swagger.jl/blob/453ad5f1405be17309e0ce987fb370bee2a89f22/.github/workflows/ci.yml#L27 and https://github.com/JuliaComputing/Swagger.jl/blob/453ad5f1405be17309e0ce987fb370bee2a89f22/.github/workflows/ci.yml#L40

**Comment by ebigram** [comment]
Thanks, I'll double-check the spec file, I did validate it but it moved around so maybe introduced some weird editor encoding artifact 🤷 (?) At least I know where to look. Thanks, I'll try a fresh spec, or at least pare down this one to see if the error can be pinpointed. Yes, I doubt it's some maven/java compatibility matrix issue as well, but I was growing desperate.

**Comment by ebigram** [comment]
Please close this out, it was some gremlins-type issue. Wish I could tell you what finally made it work, but I haven't a clue really. Must have been some artifact introduced in copying the file or some editor the first time compounded by some other latent variable. Came back to it after a week or so and it works fine; it wouldn't be related to this latest release I reckon?
