### ISSUE TITLE
Build Failure with build.sh

### ISSUE THREAD

**Issue by MaciekLeks** [JuliaComputing/Swagger.jl#7]
I've got such a "cockroach" while building the jar file:
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building julia-swagger-codegen 0.0.1
[INFO] ------------------------------------------------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/build-helper-maven-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.codehaus.mojo:build-helper-maven-plugin/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.272 s
[INFO] Finished at: 2018-06-10T10:50:24-07:00
[INFO] Final Memory: 8M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Error resolving version for plugin 'org.codehaus.mojo:build-helper-maven-plugin' from the repositories [local (/root/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginVersionResolutionException
Done
Any help appreciated.

P.S. Thanks a lot for the code generator.

**Comment by tanmaykm** [comment]
Looks like some issue with https on the local machine?

**Comment by MaciekLeks** [comment]
I've added the '-e' switch and the result is:

[ERROR] Error resolving version for plugin 'org.codehaus.mojo:build-helper-maven-plugin' from the repositories [local (/home/user/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
org.apache.maven.plugin.version.PluginVersionResolutionException: Error resolving version for plugin 'org.codehaus.mojo:build-helper-maven-plugin' from the repositories [local (/home/user/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository
    at org.apache.maven.plugin.version.internal.DefaultPluginVersionResolver.selectVersion (DefaultPluginVersionResolver.java:236)
    at org.apache.maven.plugin.version.internal.DefaultPluginVersionResolver.resolveFromRepository (DefaultPluginVersionResolver.java:146)
...

Do you still think it's the ssl problem?

P.S. I stopped working with maven 15 years ago.

**Comment by tanmaykm** [comment]
fixed in #8
