### ISSUE TITLE
Add checks to scripts to detect which OS they are being run on

### ISSUE THREAD

**Issue by jamie-arcc** [JuliaComputing/Swagger.jl#9]
Hitting a (fixable) issue running this on macOS; the default `readlink` is **BSD** readlink, not GNU, so the flags are different.  So far I've just gone in to the scripts and have replaced `readlink` with `greadlink` so it uses the GNU version, which I have installed via MacPorts.  There should either be a check for this in the scripts that use readlink, or this should be in the documentation.

**Comment by BeastyBlacksmith** [comment]
There are quite some environment assumptions for path detection. I had more luck just hardcoding the paths to
```bash
DIR="`pwd`/plugin" 
PKG_DIR="`pwd`" 
```

**Comment by tanmaykm** [comment]
fixed in #30
